### PR TITLE
Add example demonstratring how to get tracking data

### PR DESCRIPTION
**Pull request by exrook**
Minimal example that gets pose information from tracked controllers.

It does not render anything but still makes a Vulkan instance based on the vulkan.rs example.
Theoretically we could use XR_MND_headless extension if it is present but my system does not support it, nor do the current bindings.

### CODE REVIEW

**Comment by Ralith** [comment]
Rather than duplicating a significant amount of code, could we just add this to the existing example?

**Comment by exrook** [comment]
Sure, I can change it to that.
I just found the 600+ line vulkan example a little intimidating when I first found this project, and since I was only interested in getting the tracking data out I thought it would be nice to have a less involved example. Although at 400+ lines I suppose it's debatable how well this example fulfills that goal.

**Comment by Ralith** [comment]
Yeah, if it's going to be super verbose anyway--and Vulkan always is--then we might as well consolidate and save maintenance effort. Alternatively, I'd also be happy with a more focused example that targets headless mode, though indeed it needs work at the wrapper layer. I'm equipped/heappy to test against monado, if you're interested in working on that.

**Comment by exrook** [comment]
I've unified the examples now.

I may add a headless example in a future PR. I actually just tried installing monado on my laptop and it surprisingly (compared to SteamVR) just worked, although getting the vive working properly seems like it will require more effort, the example just hangs with the vive plugged in (and monado shows the vr view on my monitor instead of the hmd).

At the moment however I'm interested in getting an actual 3d example working, with proper view projection to the headset and showing the controller location/pose as cubes, so that may also come in a future PR. ...then after that I'll look at addressing https://github.com/gfx-rs/gfx/issues/3219 because "raw" vulkan really is obnoxious to work with.

**Review by Ralith — APPROVED** [review]
Thanks!

**Pull request merged**
