### PR TITLE
Make `Entry.other` public

### PR DESCRIPTION
**Pull request by Manishearth**
I'd like to be able to read from it as well when checking supported extensions

### CODE REVIEW

**Comment by Ralith** [comment]
Thanks!

**Comment by Manishearth** [comment]
Could I also get a new release with this?

**Comment by Manishearth** [comment]
lol just saw #20

**Comment by Ralith** [comment]
Yeah, we raced a bit there. I'll publish shortly.

**Comment by Manishearth** [comment]
thanks for the _extremely fast_ turnaround! :D

**Comment by Ralith** [comment]
Published in 0.12.1. Trivial fixes can be fun like that!

**Pull request merged**
