### PR TITLE
Remove `khr_vulkan_enable` support in example

### PR DESCRIPTION
**Pull request by zarik5**
All major XR runtimes have upgraded to `khr_vulkan_enable2` and new runtimes implement `khr_vulkan_enable2` directly. This change makes the example more concise and straightforward. `khr_vulkan_enable` support is kept in `openxrs` API for legacy reasons.

### CODE REVIEW

**Review by Ralith — APPROVED** [review]
Thanks!

**Comment by kanerogers** [comment]
Is this correct? The Oculus Quest (the first one) did not support enable2
last time I checked.

**Comment by Ralith** [comment]
It'd be interesting to have confirmation, but if someone really needs to target that, they can always use an old release or the raw API. This being a volunteer project I have limited bandwidth to support hardware that even first-party support has been dropped for.

**Comment by kanerogers** [comment]
I've had a think about this, @Ralith and I think you're right. 👍🏻 

We'll move to `khr_vulkan_enable2` in Hotham and drop support for the Quest.

**Pull request merged**
